#!/usr/bin/env python3
"""
Podcast Publish Pipeline — Server-side automation

Detects unprocessed scripts (scripts without matching episode YAML),
renders audio via compose.py, creates a GitHub release, rebuilds the
RSS feed, and commits the results.

Designed to run as a cron job on the second brain server.

Usage:
    python3 podcast/publish.py              # Process all pending scripts
    python3 podcast/publish.py --check      # Report pending scripts only
    python3 podcast/publish.py --no-push    # Process but don't push to remote

Environment:
    ELEVENLABS_API_KEY  — required for TTS rendering
    GITHUB_TOKEN        — required for gh release create (or gh auth)
    TELEGRAM_BOT_TOKEN  — optional, for notification via second brain
    TELEGRAM_CHAT_ID    — optional, for notification via second brain
"""

import os
import re
import sys
import subprocess
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Missing dependency: pip install PyYAML")


REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = REPO_ROOT / 'podcast' / 'scripts'
EPISODES_DIR = REPO_ROOT / 'podcast' / 'episodes'
CONFIG_PATH = REPO_ROOT / 'podcast' / '_config.yaml'


def get_pending_scripts() -> list[Path]:
    """Find scripts that don't have a matching episode YAML."""
    if not SCRIPTS_DIR.exists():
        return []

    existing_episodes = set()
    if EPISODES_DIR.exists():
        for ep_file in EPISODES_DIR.glob('*.yaml'):
            # EP001.yaml -> EP001
            existing_episodes.add(ep_file.stem)

    pending = []
    for script in sorted(SCRIPTS_DIR.glob('EP*.md')):
        # EP001-2026-04-03.md -> EP001
        episode_id = script.stem.split('-')[0]
        if episode_id not in existing_episodes:
            pending.append(script)

    return pending


def pull_latest():
    """Pull latest changes from remote."""
    print("Pulling latest from remote...")
    result = subprocess.run(
        ['git', 'pull', '--ff-only'],
        cwd=REPO_ROOT, capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"  WARNING: git pull failed: {result.stderr.strip()}")
        return False
    print(f"  {result.stdout.strip()}")
    return True


def render_episode(script_path: Path) -> tuple[Path | None, Path | None]:
    """Run compose.py on a script. Returns (audio_path, episode_yaml_path)."""
    print(f"\nRendering: {script_path.name}")
    result = subprocess.run(
        ['python3', 'podcast/compose.py', str(script_path)],
        cwd=REPO_ROOT, capture_output=True, text=True, timeout=600
    )
    print(result.stdout)
    if result.returncode != 0:
        print(f"  ERROR: compose.py failed: {result.stderr}")
        return None, None

    # Parse output to find audio and metadata paths
    audio_path = None
    yaml_path = None
    for line in result.stdout.split('\n'):
        if line.startswith('Audio: '):
            audio_path = REPO_ROOT / line.split('Audio: ')[1].strip()
        if line.startswith('Metadata: '):
            yaml_path = REPO_ROOT / line.split('Metadata: ')[1].strip()

    return audio_path, yaml_path


def create_github_release(episode_yaml: Path, audio_path: Path) -> str | None:
    """Create a GitHub release with the audio file as an asset."""
    with open(episode_yaml) as f:
        meta = yaml.safe_load(f)

    episode_id = meta.get('episode', 'EP001')
    title = meta.get('title', 'Untitled')
    date = meta.get('date', '')
    duration = meta.get('duration', '')
    sources = meta.get('sources', [])

    tag = f"podcast-{episode_id.lower()}"
    release_title = f"{episode_id}: {title}"

    source_count = len(sources) if isinstance(sources, list) else 0
    body = (
        f"## {release_title}\n\n"
        f"- **Date**: {date}\n"
        f"- **Duration**: {duration}\n"
        f"- **Sources covered**: {source_count}\n\n"
        f"Generated by the Hype Watch podcast pipeline.\n"
    )

    print(f"\nCreating GitHub release: {tag}")
    result = subprocess.run(
        ['gh', 'release', 'create', tag,
         str(audio_path),
         '--title', release_title,
         '--notes', body],
        cwd=REPO_ROOT, capture_output=True, text=True
    )

    if result.returncode != 0:
        print(f"  ERROR: gh release create failed: {result.stderr}")
        return None

    release_url = result.stdout.strip()
    print(f"  Release: {release_url}")

    # Get the asset download URL
    asset_result = subprocess.run(
        ['gh', 'release', 'view', tag, '--json', 'assets', '-q', '.assets[0].url'],
        cwd=REPO_ROOT, capture_output=True, text=True
    )
    asset_url = asset_result.stdout.strip() if asset_result.returncode == 0 else None

    # Update episode YAML with audio URL
    if asset_url:
        meta['audio_url'] = asset_url
        with open(episode_yaml, 'w') as f:
            yaml.dump(meta, f, default_flow_style=False, sort_keys=False)

    return release_url


def build_feed():
    """Rebuild the RSS feed."""
    feed_script = REPO_ROOT / 'podcast' / 'build-feed.py'
    if not feed_script.exists():
        print("  Skipping feed build — build-feed.py not found")
        return

    print("\nRebuilding RSS feed...")
    result = subprocess.run(
        ['python3', str(feed_script)],
        cwd=REPO_ROOT, capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"  ERROR: feed build failed: {result.stderr}")
    else:
        print(f"  {result.stdout.strip()}")


def commit_and_push(episode_ids: list[str], no_push: bool = False):
    """Commit episode metadata and feed, push to remote."""
    # Stage episode files and feed
    subprocess.run(
        ['git', 'add', 'podcast/episodes/', 'podcast/feed.xml'],
        cwd=REPO_ROOT, capture_output=True
    )

    # Check if there's anything to commit
    status = subprocess.run(
        ['git', 'status', '--porcelain', 'podcast/episodes/', 'podcast/feed.xml'],
        cwd=REPO_ROOT, capture_output=True, text=True
    )
    if not status.stdout.strip():
        print("\nNo changes to commit.")
        return

    ids = ', '.join(episode_ids)
    msg = f"podcast: publish {ids}"
    subprocess.run(
        ['git', 'commit', '-m', msg],
        cwd=REPO_ROOT, capture_output=True, text=True
    )
    print(f"\nCommitted: {msg}")

    if no_push:
        print("  --no-push: skipping push")
        return

    result = subprocess.run(
        ['git', 'push'],
        cwd=REPO_ROOT, capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"  WARNING: push failed: {result.stderr}")
    else:
        print("  Pushed to remote.")


def notify(message: str):
    """Send notification via Telegram if configured."""
    token = os.environ.get('TELEGRAM_BOT_TOKEN')
    chat_id = os.environ.get('TELEGRAM_CHAT_ID')
    if not token or not chat_id:
        return

    import urllib.request
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = json.dumps({"chat_id": chat_id, "text": message, "parse_mode": "Markdown"}).encode()
    req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})
    try:
        urllib.request.urlopen(req, timeout=10)
    except Exception as e:
        print(f"  WARNING: Telegram notification failed: {e}")


def main():
    check_only = '--check' in sys.argv
    no_push = '--no-push' in sys.argv

    # Pull latest
    if not check_only:
        pull_latest()

    # Find pending scripts
    pending = get_pending_scripts()

    if not pending:
        print("No pending podcast scripts found.")
        return

    print(f"Found {len(pending)} pending script(s):")
    for s in pending:
        print(f"  - {s.name}")

    if check_only:
        return

    # Check dependencies
    if not os.environ.get('ELEVENLABS_API_KEY'):
        sys.exit("ELEVENLABS_API_KEY not set.")

    # Process each pending script
    published = []
    for script in pending:
        audio_path, episode_yaml = render_episode(script)
        if not audio_path or not episode_yaml:
            print(f"  Skipping {script.name} — render failed")
            continue

        release_url = create_github_release(episode_yaml, audio_path)

        # Clean up audio files (large, don't need to keep on server)
        audio_dir = audio_path.parent
        if audio_dir.exists():
            for f in audio_dir.iterdir():
                f.unlink()
            audio_dir.rmdir()

        episode_id = script.stem.split('-')[0]
        published.append(episode_id)

        if release_url:
            # Read episode meta for notification
            with open(episode_yaml) as f:
                meta = yaml.safe_load(f)
            notify(
                f"🎙 *Hype Watch {episode_id}* published\n"
                f"_{meta.get('title', '')}_\n"
                f"Duration: {meta.get('duration', 'unknown')}\n"
                f"{release_url}"
            )

    if published:
        build_feed()
        commit_and_push(published, no_push=no_push)

    print(f"\nDone. Published: {', '.join(published) if published else 'none'}")


if __name__ == '__main__':
    import json  # needed for notify
    main()
